name = "PandocFiltersLiveJuliaCode"
uuid = "f2a155ab-7813-4802-b03c-37488dc6a1bf"
authors = ["Hiroharu Sugawara <hsugawa@gmail.com> and contributors"]
version = "0.2.1"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
JSON = "0.21"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
